ITERATION_LEARNING = 1500
LEARNING_RATE = 0.1

PROBABILTY_EXPLORE = 0.1
PROBABILTY_EXPLORE_IN_OPTION = 0.1

ZONE_SIZE_X = 8
ZONE_SIZE_Y = 8
NUMBER_GRAY_COLORS = 10

REWARD_END_OPTION = 2
REWARD_AGENT = -1
REWARD_KEY = 10

MAXIMUM_EXPLORATION = 500
