ITERATION_LEARNING = 700 #161 is enough for Q learning
LEARNING_RATE = 0.1

PROBABILTY_EXPLORE = 0.5
PROBABILTY_EXPLORE_IN_OPTION = 0.0

ZONE_SIZE_X = 4
ZONE_SIZE_Y = 4
NUMBER_GRAY_COLORS = 10

REWARD_END_OPTION = 1
PENALTY_END_OPTION = 1
REWARD_ACTION = 0
REWARD_AGENT_ACTION = 0
REWARD_OPTION_ACTION = 0
REWARD_KEY = 1

NUMBER_ACTIONS = 4
