ITERATION_LEARNING = 2000
LEARNING_RATE = 0.2

PROBABILTY_EXPLORE = 0.2
PROBABILTY_EXPLORE_IN_OPTION = 0.1

ZONE_SIZE_X = 4
ZONE_SIZE_Y = 2
NUMBER_GRAY_COLORS = 10

REWARD_END_OPTION = 1
REWARD_AGENT = -1
REWARD_KEY = 10

